// ShaderInjectorVersion.h
#pragma once

// Keep the numeric and string forms synchronized. Windows VERSIONINFO requires
// the numeric form while Explorer displays the string form.
#define SHADER_INJECTOR_VERSION_MAJOR 1
#define SHADER_INJECTOR_VERSION_MINOR 0
#define SHADER_INJECTOR_VERSION_PATCH 0
#define SHADER_INJECTOR_VERSION_BUILD 0

#define SHADER_INJECTOR_VERSION_NUMERIC \
	SHADER_INJECTOR_VERSION_MAJOR, SHADER_INJECTOR_VERSION_MINOR, SHADER_INJECTOR_VERSION_PATCH, SHADER_INJECTOR_VERSION_BUILD

#define SHADER_INJECTOR_VERSION_STRING "1.0.0.0"
